### PR TITLE
Archrebuild

### PR DESCRIPTION
**Pull request by h-vetinari**
Rebuild pythran for ppc/aarch, needed for scipy 1.7.0: https://github.com/conda-forge/scipy-feedstock/pull/169

### CODE REVIEW

**Comment by h-vetinari** [comment]
@serge-sans-paille
Not sure if xsimd even makes sense for aarch / ppc (at least the latter doesn't seem supported [upstream](https://github.com/xtensor-stack/xsimd))? Since it's skipped on windows already, I'm hoping it's not mandatory?

**Comment by h-vetinari** [comment]
Sounds like the tests currently use incompatible arguments:
```
powerpc64le-conda-linux-gnu-c++: error: unrecognized command line option '-march=native'; did you mean '-mcpu=native'?
```

**Comment by serge-sans-paille** [comment]
Yeah, you can disable -march=native and -DUSE_XSIMD on ppc, it's not a supported target of xsimd.

**Comment by h-vetinari** [comment]
OK cool, thanks for the info.

However, the tests still seem to be looking for xsimd headers, even though I deactivated `-DUSE_XSMID` already in https://github.com/conda-forge/pythran-feedstock/pull/46/commits/5e7c233f5bb9a1589055c568db5aeaa7eedfad74:
```
[...]/site-packages/pythran/pythonic/include/numpy/maximum.hpp:9:10: fatal error: xsimd/xsimd.hpp: No such file or directory
    9 | #include <xsimd/xsimd.hpp>
      |          ^~~~~~~~~~~~~~~~~
```

**Comment by serge-sans-paille** [comment]
So the problem that remains is: why is xsimd not packaged everywhere? It should be avialble on ppc, just for its scalar version.

**Comment by serge-sans-paille** [comment]
I've pinged xsimd's maintainer to fix that, should be okay once they rebuild

**Comment by h-vetinari** [comment]
That's a very swift response indeed - https://github.com/conda-forge/xsimd-feedstock/pull/72 - thanks for tackling this @JohanMabille!

**Comment by JohanMabille** [comment]
Hi there, I was about to comment here when the light are green ;) I have an additional PR to open to conda-forge to trigger the aarch64 build.

**Comment by h-vetinari** [comment]
@serge-sans-paille, fails on ppc (but passes on aarch):
```
/home/[...]/site-packages/pythran/pythonic/numpy/reduce.hpp:80:25: error: 'size' is not a member of 'vT' {aka 'double'}
   80 |     static const size_t vN = vT::size;
      |                         ^~
/home/[...]/site-packages/pythran/pythonic/numpy/reduce.hpp:88:36: error: size of array is not an integral constant-expression
   88 |       alignas(sizeof(vT)) T stored[vN];
      |                                    ^~
/home/[...]/site-packages/pythran/pythonic/numpy/reduce.hpp:89:12: error: request for member 'store_aligned' in 'vacc', which is of non-class type 'double'
   89 |       vacc.store_aligned(&stored[0]);
      |       ~~~~~^~~~~~~~~~~~~
WARNING: Compilation error, trying hard to find its origin...
WARNING: Nop, I'm going to flood you with C++ errors!
CRITICAL: Cover me Jack. Jack? Jaaaaack!!!!
E: error: Command "/home/conda/feedstock_root/build_artifacts/pythran_1623064281526
```

**Comment by serge-sans-paille** [comment]
@h-vetinari that may be a portability issue on pythran side, I'll investigate

**Comment by h-vetinari** [comment]
> 
> 
> @h-vetinari that may be a portability issue on pythran side, I'll investigate

Thanks a lot! (that's what it looked like to me as well, hence why I pinged you 🙃)

**Comment by serge-sans-paille** [comment]
greeen \o/

**Comment by h-vetinari** [comment]
Cool! Good to merge from my side.

**Comment by h-vetinari** [comment]
Though we should probably bump the build number...

(windows dependency changed to explicitly include `xsimd` - though I don't know how that passed the tests before...)

**Comment by h-vetinari** [comment]
You can add the automerge-label if you don't want to babysit the CI... 🤷

**Pull request merged**
