### PR TITLE
Rebuild for PyPy3.7 for windows (redux)

### PR DESCRIPTION
**Pull request by h-vetinari**
Closes #51

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
I honestly don't have any opinion on that one, except that the Travis builder needs a rebuild :-)

**Comment by serge-sans-paille** [comment]
Rebuilt, feel free to merge when needs be.

**Comment by h-vetinari** [comment]
I'm not in the core team, so I cannot merge PRs on feedstocks where I'm not maintainer. Could you press the button please?

**Comment by h-vetinari** [comment]
@serge-sans-paille, could you merge this please?

**Pull request merged**
