### PR TITLE
Relax C++ compiler pin

### PR DESCRIPTION
**Pull request by saraedum**
The runtime dependencies of pythran had `compiler('cxx')`. The intention
here was to make sure that some C++ compiler is available. However, this
actually forces this to be the compiler that was used when building the
package, i.e., GCC 9. This causes trouble when trying to install a
package that requires a newer compiler at the same time, e.g., when
installing `cppyy=2.3.0` and `pythran=0.11.0`.

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by serge-sans-paille** [comment]
I understand the issue... I trust you on that one. Maybe require either clang++ or g++ ?

**Comment by saraedum** [comment]
Are these the only C++ compilers that are going to work?

**Comment by serge-sans-paille** [comment]
On Wed, Mar 16, 2022 at 05:38:12PM -0700, Julian Rüth wrote:
> Are these the only C++ compilers that are going to work?

That's the only I have tested :-)

**Pull request closed without merging**
